### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by sialvsic** [hifeteam/cat-ui#106]
Issue:
ReferenceError: window is not defined
    at new MediaQueryDispatch (/Users/yxzhou/Workspace/official-project/ximalaya/hmly-web/node_modules/enquire.js/src/MediaQueryDispatch.js:14:5)
    at Object.<anonymous> (/Users/yxzhou/Workspace/official-project/ximalaya/hmly-web/node_modules/enquire.js/src/index.js:2:18)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/yxzhou/Workspace/official-project/ximalaya/hmly-web/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yxzhou/Workspace/official-project/ximalaya/hmly-web/node_modules/@hife/catui/src/components/Row/Row.tsx:6:1)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/yxzhou/Workspace/official-project/ximalaya/hmly-web/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)

reason: window is not defined 
enquire.js 不支持服务端渲染

**Comment by sialvsic** [comment]
@hileix

**Comment by hileix** [comment]
👌
